language: cpp
sudo: required
dist: trusty
cache:
  bundler: true
  directories:
  - petsc-3.5.4
addons:
  apt:
    packages:
    - cmake
    - libopenmpi-dev
    - openmpi-bin
    - libboost-test-dev
    sources:
    - ubuntu-toolchain-r-test
compiler:
- mpicxx
os:
- linux
before_install:
- ./scripts/dependencies.sh
script:
- ./scripts/build.sh
env:
  global:
