language: cpp
sudo: required
dist: trusty
cache:
  bundler: true
  directories:
  - petsc-3.5.4
addons:
  apt:
    packages:
    - cmake
    sources:
    - ubuntu-toolchain-r-test
compiler:
- mpicxx
os:
- linux
before_install:
- test -n $CC  && unset CC
- test -n $CXX && unset CXX
- ./scripts/dependencies.sh
install:
- sudo apt-get update -qq
- sudo apt-get install -qq g++-5
script:
- ./scripts/build.sh
env:
  global: